version: "3.9"

services:
  user_container:
    container_name: "user_container"   # will be overridden in launch script
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - USER_NAME
      - USER_EMAIL
      - USER_PASSWORD
    stdin_open: true
    tty: true
    restart: always
    networks:
      - securedrop_lan

networks:
  securedrop_lan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          ip_range: 192.168.1.200/29
          gateway: 192.168.1.1