version: "3.9"

services:
  securedrop_user:
    container_name: "securedrop_user"
    image: securedrop-docker_user_container:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - USER_NAME=${USER_NAME}
      - USER_PASSWORD=${USER_PASSWORD}
    volumes:
      - securedrop_auth:/app/auth       # Shared authentication database
      - securedrop_data:/app/data       # Shared data root (per-user directories)
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - securedrop_lan

volumes:
  securedrop_auth:
    name: securedrop_auth
  securedrop_data:
    name: securedrop_data

networks:
  securedrop_lan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          ip_range: 192.168.1.200/29
          gateway: 192.168.1.1
