version: "3.9"

services:
  host:
    container_name: host_container
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 securedrop.py
    volumes:
      - securedrop_auth:/app/auth
      - securedrop_data:/app/data
    stdin_open: true
    tty: true
    restart: always
    networks:
      - securedrop_bridge

  receiver:
    container_name: receiver_container
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 securedrop.py
    volumes:
      - securedrop_auth:/app/auth
      - securedrop_data:/app/data
    stdin_open: true
    tty: true
    restart: always
    networks:
      - securedrop_bridge

volumes:
  securedrop_auth:
    name: securedrop_auth
  securedrop_data:
    name: securedrop_data

networks:
  securedrop_bridge:
    driver: bridge