services:
  host:
    container_name: host_container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - USER_NAME=host
      - USER_PASSWORD=hostpass
      - USER_EMAIL=host@example.com
    volumes:
      - ./data:/app/data
    command: python3 securedrop.py host
    networks:
      - securedrop_bridge
    restart: always

  receiver:
    container_name: receiver_container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - USER_NAME=receiver
      - USER_PASSWORD=receiverpass
      - USER_EMAIL=receiver@example.com
    volumes:
      - ./data:/app/data
    command: python3 securedrop.py receiver
    networks:
      - securedrop_bridge
    restart: always

networks:
  securedrop_bridge:
    driver: bridge