version: "3.9"

services:
  host:
    container_name: host_container
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 securedrop.py
    volumes:
      - securedrop_auth:/app/auth
      - securedrop_data:/app/data
    stdin_open: true
    tty: true
    restart: always
    networks:
      securedrop_lan:
        ipv4_address: 192.168.1.201  # unique IP for this container

  receiver:
    container_name: receiver_container
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 securedrop.py
    volumes:
      - securedrop_auth:/app/auth
      - securedrop_data:/app/data
    stdin_open: true
    tty: true
    restart: always
    networks:
      securedrop_lan:
        ipv4_address: 192.168.1.202  # unique IP for this container

volumes:
  securedrop_auth:
    name: securedrop_auth
  securedrop_data:
    name: securedrop_data

networks:
  securedrop_lan:
    driver: macvlan
    driver_opts:
      parent: eth0  # replace with your actual host interface
    ipam:
      config:
        - subnet: 192.168.1.0/24       # Your LAN subnet
          ip_range: 192.168.1.200/29   # Small range for containers only
          # DO NOT specify gateway to avoid conflicts