services:
  host:
    container_name: host_container
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 securedrop.py host
    volumes:
      - ./auth:/app/auth        # bind mount to host folder ./auth
      - ./data:/app/data        # bind mount to host folder ./data
    stdin_open: true
    tty: true
    restart: always
    networks:
      - securedrop_bridge

  receiver:
    container_name: receiver_container
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 securedrop.py receiver
    volumes:
      - ./auth:/app/auth
      - ./data:/app/data
    stdin_open: true
    tty: true
    restart: always
    networks:
      - securedrop_bridge

networks:
  securedrop_bridge:
    driver: bridge