version: "3.9"

services:
  host:
    container_name: host
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 securedrop.py
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    restart: always
    networks:
      - securedrop_lan

  receiver:
    container_name: receiver
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 securedrop.py
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    restart: always
    networks:
      - securedrop_lan

networks:
  securedrop_lan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          ip_range: 192.168.1.200/29
          gateway: 192.168.1.1